# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\AG\.qgis2\python\plugins\SeismicRisk\SeismicRisk_dockwidget_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SeismicRisk_dockwidget_base(object):
    def setupUi(self, SeismicRisk_dockwidget_base):
        SeismicRisk_dockwidget_base.setObjectName(_fromUtf8("SeismicRisk_dockwidget_base"))
        SeismicRisk_dockwidget_base.resize(1016, 880)
        SeismicRisk_dockwidget_base.setMaximumSize(QtCore.QSize(524287, 524287))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 992, 830))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.PredictionModel = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.PredictionModel.setEnabled(True)
        self.PredictionModel.setGeometry(QtCore.QRect(0, 0, 911, 751))
        self.PredictionModel.setObjectName(_fromUtf8("PredictionModel"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_28 = QtGui.QLabel(self.tab_3)
        self.label_28.setGeometry(QtCore.QRect(90, 50, 111, 20))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.layersTableView = QtGui.QTableWidget(self.tab_3)
        self.layersTableView.setGeometry(QtCore.QRect(90, 140, 401, 241))
        self.layersTableView.setObjectName(_fromUtf8("layersTableView"))
        self.layersTableView.setColumnCount(0)
        self.layersTableView.setRowCount(0)
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(90, 100, 91, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushLayerButton = QtGui.QPushButton(self.tab_3)
        self.pushLayerButton.setGeometry(QtCore.QRect(110, 410, 93, 28))
        self.pushLayerButton.setObjectName(_fromUtf8("pushLayerButton"))
        self.lineEdit_4 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(190, 50, 251, 22))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.typeLayerComboBox = QtGui.QComboBox(self.tab_3)
        self.typeLayerComboBox.setGeometry(QtCore.QRect(210, 90, 211, 22))
        self.typeLayerComboBox.setObjectName(_fromUtf8("typeLayerComboBox"))
        self.eraseLayerButton = QtGui.QPushButton(self.tab_3)
        self.eraseLayerButton.setGeometry(QtCore.QRect(240, 410, 93, 28))
        self.eraseLayerButton.setObjectName(_fromUtf8("eraseLayerButton"))
        self.updateLayerButton = QtGui.QPushButton(self.tab_3)
        self.updateLayerButton.setGeometry(QtCore.QRect(370, 410, 93, 28))
        self.updateLayerButton.setObjectName(_fromUtf8("updateLayerButton"))
        self.alignLayerspushButton = QtGui.QPushButton(self.tab_3)
        self.alignLayerspushButton.setGeometry(QtCore.QRect(110, 490, 131, 28))
        self.alignLayerspushButton.setObjectName(_fromUtf8("alignLayerspushButton"))
        self.PredictionModel.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(70, 90, 51, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.IdHazardComboBox = QtGui.QComboBox(self.tab)
        self.IdHazardComboBox.setGeometry(QtCore.QRect(120, 100, 201, 21))
        self.IdHazardComboBox.setObjectName(_fromUtf8("IdHazardComboBox"))
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(100, 50, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.hazardModelWidget = QtGui.QWidget(self.tab)
        self.hazardModelWidget.setGeometry(QtCore.QRect(50, 480, 481, 211))
        self.hazardModelWidget.setObjectName(_fromUtf8("hazardModelWidget"))
        self.label_29 = QtGui.QLabel(self.hazardModelWidget)
        self.label_29.setGeometry(QtCore.QRect(-20, 30, 131, 61))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.hazardModelTextEdit = QtGui.QTextEdit(self.hazardModelWidget)
        self.hazardModelTextEdit.setGeometry(QtCore.QRect(120, 50, 301, 41))
        self.hazardModelTextEdit.setObjectName(_fromUtf8("hazardModelTextEdit"))
        self.label_30 = QtGui.QLabel(self.hazardModelWidget)
        self.label_30.setGeometry(QtCore.QRect(30, 100, 131, 21))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.valuesHazardModelTextEdit = QtGui.QTextEdit(self.hazardModelWidget)
        self.valuesHazardModelTextEdit.setGeometry(QtCore.QRect(120, 100, 301, 41))
        self.valuesHazardModelTextEdit.setObjectName(_fromUtf8("valuesHazardModelTextEdit"))
        self.saveHazardModelButton = QtGui.QPushButton(self.hazardModelWidget)
        self.saveHazardModelButton.setGeometry(QtCore.QRect(300, 160, 93, 28))
        self.saveHazardModelButton.setObjectName(_fromUtf8("saveHazardModelButton"))
        self.widgetHazardValues = QtGui.QWidget(self.tab)
        self.widgetHazardValues.setGeometry(QtCore.QRect(40, 150, 301, 171))
        self.widgetHazardValues.setObjectName(_fromUtf8("widgetHazardValues"))
        self.label_13 = QtGui.QLabel(self.widgetHazardValues)
        self.label_13.setGeometry(QtCore.QRect(20, 20, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.hazardValueLineEdit = QtGui.QLineEdit(self.widgetHazardValues)
        self.hazardValueLineEdit.setGeometry(QtCore.QRect(110, 20, 161, 22))
        self.hazardValueLineEdit.setObjectName(_fromUtf8("hazardValueLineEdit"))
        self.label_32 = QtGui.QLabel(self.widgetHazardValues)
        self.label_32.setGeometry(QtCore.QRect(60, 60, 53, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.RvalueLineEdit = QtGui.QLineEdit(self.widgetHazardValues)
        self.RvalueLineEdit.setGeometry(QtCore.QRect(110, 50, 161, 22))
        self.RvalueLineEdit.setObjectName(_fromUtf8("RvalueLineEdit"))
        self.label_33 = QtGui.QLabel(self.widgetHazardValues)
        self.label_33.setGeometry(QtCore.QRect(60, 90, 53, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.SoilLineEdit = QtGui.QLineEdit(self.widgetHazardValues)
        self.SoilLineEdit.setGeometry(QtCore.QRect(110, 90, 161, 22))
        self.SoilLineEdit.setObjectName(_fromUtf8("SoilLineEdit"))
        self.saveHazardParametersPushButton = QtGui.QPushButton(self.widgetHazardValues)
        self.saveHazardParametersPushButton.setGeometry(QtCore.QRect(180, 130, 93, 28))
        self.saveHazardParametersPushButton.setObjectName(_fromUtf8("saveHazardParametersPushButton"))
        self.widget_Epicenter = QtGui.QWidget(self.tab)
        self.widget_Epicenter.setGeometry(QtCore.QRect(440, 190, 291, 131))
        self.widget_Epicenter.setObjectName(_fromUtf8("widget_Epicenter"))
        self.widget_LoadHazardModel = QtGui.QWidget(self.tab)
        self.widget_LoadHazardModel.setGeometry(QtCore.QRect(60, 410, 441, 121))
        self.widget_LoadHazardModel.setObjectName(_fromUtf8("widget_LoadHazardModel"))
        self.label_12 = QtGui.QLabel(self.widget_LoadHazardModel)
        self.label_12.setGeometry(QtCore.QRect(10, 40, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.loadHazardButton = QtGui.QPushButton(self.widget_LoadHazardModel)
        self.loadHazardButton.setGeometry(QtCore.QRect(90, 80, 93, 28))
        self.loadHazardButton.setObjectName(_fromUtf8("loadHazardButton"))
        self.calculateHarzadPushButton = QtGui.QPushButton(self.widget_LoadHazardModel)
        self.calculateHarzadPushButton.setGeometry(QtCore.QRect(190, 80, 93, 30))
        self.calculateHarzadPushButton.setObjectName(_fromUtf8("calculateHarzadPushButton"))
        self.hazardModelComboBox = QtGui.QComboBox(self.widget_LoadHazardModel)
        self.hazardModelComboBox.setGeometry(QtCore.QRect(110, 40, 291, 22))
        self.hazardModelComboBox.setObjectName(_fromUtf8("hazardModelComboBox"))
        self.hazardObjectsComboBox = QtGui.QComboBox(self.widget_LoadHazardModel)
        self.hazardObjectsComboBox.setGeometry(QtCore.QRect(110, 10, 291, 22))
        self.hazardObjectsComboBox.setObjectName(_fromUtf8("hazardObjectsComboBox"))
        self.label_35 = QtGui.QLabel(self.widget_LoadHazardModel)
        self.label_35.setGeometry(QtCore.QRect(0, 10, 91, 20))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_34 = QtGui.QLabel(self.tab)
        self.label_34.setGeometry(QtCore.QRect(60, 370, 53, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.LoadEpicenterpushButton = QtGui.QPushButton(self.tab)
        self.LoadEpicenterpushButton.setGeometry(QtCore.QRect(390, 370, 93, 28))
        self.LoadEpicenterpushButton.setObjectName(_fromUtf8("LoadEpicenterpushButton"))
        self.epicenterLineEdit = QtGui.QLineEdit(self.tab)
        self.epicenterLineEdit.setGeometry(QtCore.QRect(120, 370, 261, 21))
        self.epicenterLineEdit.setObjectName(_fromUtf8("epicenterLineEdit"))
        self.label_31 = QtGui.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(90, 330, 53, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.MomentumLineEdit = QtGui.QLineEdit(self.tab)
        self.MomentumLineEdit.setGeometry(QtCore.QRect(120, 330, 161, 22))
        self.MomentumLineEdit.setObjectName(_fromUtf8("MomentumLineEdit"))
        self.PredictionModel.addTab(self.tab, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.resilienceButton = QtGui.QPushButton(self.tab_4)
        self.resilienceButton.setGeometry(QtCore.QRect(100, 350, 191, 41))
        self.resilienceButton.setObjectName(_fromUtf8("resilienceButton"))
        self.label_9 = QtGui.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(10, 90, 21, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.deleteButton = QtGui.QPushButton(self.tab_4)
        self.deleteButton.setGeometry(QtCore.QRect(190, 150, 75, 23))
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.readButton = QtGui.QPushButton(self.tab_4)
        self.readButton.setGeometry(QtCore.QRect(190, 120, 75, 23))
        self.readButton.setObjectName(_fromUtf8("readButton"))
        self.pushButton = QtGui.QPushButton(self.tab_4)
        self.pushButton.setGeometry(QtCore.QRect(190, 90, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tableViewMethodology = QtGui.QTableWidget(self.tab_4)
        self.tableViewMethodology.setGeometry(QtCore.QRect(30, 450, 241, 81))
        self.tableViewMethodology.setObjectName(_fromUtf8("tableViewMethodology"))
        self.tableViewMethodology.setColumnCount(0)
        self.tableViewMethodology.setRowCount(0)
        self.idComboBox = QtGui.QComboBox(self.tab_4)
        self.idComboBox.setGeometry(QtCore.QRect(30, 90, 141, 22))
        self.idComboBox.setObjectName(_fromUtf8("idComboBox"))
        self.updateValutazione = QtGui.QPushButton(self.tab_4)
        self.updateValutazione.setGeometry(QtCore.QRect(30, 120, 121, 21))
        self.updateValutazione.setObjectName(_fromUtf8("updateValutazione"))
        self.label_7 = QtGui.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(90, 410, 121, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tableWidgetParameters = QtGui.QTableWidget(self.tab_4)
        self.tableWidgetParameters.setGeometry(QtCore.QRect(30, 210, 231, 101))
        self.tableWidgetParameters.setObjectName(_fromUtf8("tableWidgetParameters"))
        self.tableWidgetParameters.setColumnCount(0)
        self.tableWidgetParameters.setRowCount(0)
        self.label_8 = QtGui.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(90, 190, 181, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label = QtGui.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(20, 320, 71, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit = QtGui.QLineEdit(self.tab_4)
        self.lineEdit.setGeometry(QtCore.QRect(90, 320, 161, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_17 = QtGui.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(60, 40, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.PredictionModel.addTab(self.tab_4, _fromUtf8(""))
        self.vulnerabilitydetailsttab = QtGui.QWidget()
        self.vulnerabilitydetailsttab.setObjectName(_fromUtf8("vulnerabilitydetailsttab"))
        self.tabWidget = QtGui.QTabWidget(self.vulnerabilitydetailsttab)
        self.tabWidget.setGeometry(QtCore.QRect(40, 20, 741, 691))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_13 = QtGui.QWidget()
        self.tab_13.setEnabled(True)
        self.tab_13.setObjectName(_fromUtf8("tab_13"))
        self.formLayout = QtGui.QFormLayout(self.tab_13)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_69 = QtGui.QLabel(self.tab_13)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_69)
        self.lineEdit_9 = QtGui.QLineEdit(self.tab_13)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_9)
        self.tabWidget.addTab(self.tab_13, _fromUtf8(""))
        self.tab_14 = QtGui.QWidget()
        self.tab_14.setObjectName(_fromUtf8("tab_14"))
        self.tableWidget_5 = QtGui.QTableWidget(self.tab_14)
        self.tableWidget_5.setGeometry(QtCore.QRect(70, 40, 491, 471))
        self.tableWidget_5.setObjectName(_fromUtf8("tableWidget_5"))
        self.tableWidget_5.setColumnCount(3)
        self.tableWidget_5.setRowCount(14)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        self.buttonBox_3 = QtGui.QDialogButtonBox(self.tab_14)
        self.buttonBox_3.setGeometry(QtCore.QRect(370, 530, 193, 28))
        self.buttonBox_3.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_3.setObjectName(_fromUtf8("buttonBox_3"))
        self.tabWidget.addTab(self.tab_14, _fromUtf8(""))
        self.tab_15 = QtGui.QWidget()
        self.tab_15.setObjectName(_fromUtf8("tab_15"))
        self.tableWidget_4 = QtGui.QTableWidget(self.tab_15)
        self.tableWidget_4.setGeometry(QtCore.QRect(90, 40, 491, 471))
        self.tableWidget_4.setObjectName(_fromUtf8("tableWidget_4"))
        self.tableWidget_4.setColumnCount(4)
        self.tableWidget_4.setRowCount(14)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        self.buttonBox_2 = QtGui.QDialogButtonBox(self.tab_15)
        self.buttonBox_2.setGeometry(QtCore.QRect(390, 530, 193, 28))
        self.buttonBox_2.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName(_fromUtf8("buttonBox_2"))
        self.tabWidget.addTab(self.tab_15, _fromUtf8(""))
        self.tab_16 = QtGui.QWidget()
        self.tab_16.setObjectName(_fromUtf8("tab_16"))
        self.tableWidget_3 = QtGui.QTableWidget(self.tab_16)
        self.tableWidget_3.setGeometry(QtCore.QRect(30, 40, 491, 471))
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(14)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.buttonBox = QtGui.QDialogButtonBox(self.tab_16)
        self.buttonBox.setGeometry(QtCore.QRect(380, 530, 193, 28))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tabWidget.addTab(self.tab_16, _fromUtf8(""))
        self.PredictionModel.addTab(self.vulnerabilitydetailsttab, _fromUtf8(""))
        self.vulnerability2tab = QtGui.QWidget()
        self.vulnerability2tab.setObjectName(_fromUtf8("vulnerability2tab"))
        self.label_14 = QtGui.QLabel(self.vulnerability2tab)
        self.label_14.setGeometry(QtCore.QRect(110, 90, 31, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.idVulnerabilityCurvesComboBox = QtGui.QComboBox(self.vulnerability2tab)
        self.idVulnerabilityCurvesComboBox.setGeometry(QtCore.QRect(290, 90, 241, 22))
        self.idVulnerabilityCurvesComboBox.setObjectName(_fromUtf8("idVulnerabilityCurvesComboBox"))
        self.label_15 = QtGui.QLabel(self.vulnerability2tab)
        self.label_15.setGeometry(QtCore.QRect(110, 140, 121, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.typeBuildingsVulnerabilityCurvesComboBox_2 = QtGui.QComboBox(self.vulnerability2tab)
        self.typeBuildingsVulnerabilityCurvesComboBox_2.setGeometry(QtCore.QRect(290, 140, 241, 22))
        self.typeBuildingsVulnerabilityCurvesComboBox_2.setObjectName(_fromUtf8("typeBuildingsVulnerabilityCurvesComboBox_2"))
        self.label_18 = QtGui.QLabel(self.vulnerability2tab)
        self.label_18.setGeometry(QtCore.QRect(170, 40, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_27 = QtGui.QLabel(self.vulnerability2tab)
        self.label_27.setGeometry(QtCore.QRect(110, 190, 53, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.selectCurvescomboBox = QtGui.QComboBox(self.vulnerability2tab)
        self.selectCurvescomboBox.setGeometry(QtCore.QRect(290, 190, 241, 22))
        self.selectCurvescomboBox.setObjectName(_fromUtf8("selectCurvescomboBox"))
        self.verticalLayoutWidget = QtGui.QWidget(self.vulnerability2tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 440, 561, 261))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.layoutPlot = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.layoutPlot.setObjectName(_fromUtf8("layoutPlot"))
        self.label_36 = QtGui.QLabel(self.vulnerability2tab)
        self.label_36.setGeometry(QtCore.QRect(110, 350, 171, 20))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.vulnerability2tab)
        self.label_37.setGeometry(QtCore.QRect(120, 390, 101, 20))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.levelDamagesComboBox = QtGui.QComboBox(self.vulnerability2tab)
        self.levelDamagesComboBox.setGeometry(QtCore.QRect(230, 390, 231, 22))
        self.levelDamagesComboBox.setObjectName(_fromUtf8("levelDamagesComboBox"))
        self.generateMapByCurveButton = QtGui.QPushButton(self.vulnerability2tab)
        self.generateMapByCurveButton.setGeometry(QtCore.QRect(480, 390, 131, 28))
        self.generateMapByCurveButton.setObjectName(_fromUtf8("generateMapByCurveButton"))
        self.earthquakeIntensityVulverabilityCurvesText = QtGui.QLineEdit(self.vulnerability2tab)
        self.earthquakeIntensityVulverabilityCurvesText.setGeometry(QtCore.QRect(290, 350, 113, 22))
        self.earthquakeIntensityVulverabilityCurvesText.setObjectName(_fromUtf8("earthquakeIntensityVulverabilityCurvesText"))
        self.assignFragilityPushButton = QtGui.QPushButton(self.vulnerability2tab)
        self.assignFragilityPushButton.setGeometry(QtCore.QRect(540, 190, 131, 28))
        self.assignFragilityPushButton.setObjectName(_fromUtf8("assignFragilityPushButton"))
        self.addFragilityCurveButton = QtGui.QPushButton(self.vulnerability2tab)
        self.addFragilityCurveButton.setGeometry(QtCore.QRect(260, 280, 161, 28))
        self.addFragilityCurveButton.setObjectName(_fromUtf8("addFragilityCurveButton"))
        self.deleteFragilityCurvesButton = QtGui.QPushButton(self.vulnerability2tab)
        self.deleteFragilityCurvesButton.setGeometry(QtCore.QRect(430, 280, 161, 28))
        self.deleteFragilityCurvesButton.setObjectName(_fromUtf8("deleteFragilityCurvesButton"))
        self.showAssignedFragilitiesButton = QtGui.QPushButton(self.vulnerability2tab)
        self.showAssignedFragilitiesButton.setGeometry(QtCore.QRect(540, 140, 161, 28))
        self.showAssignedFragilitiesButton.setObjectName(_fromUtf8("showAssignedFragilitiesButton"))
        self.label_38 = QtGui.QLabel(self.vulnerability2tab)
        self.label_38.setGeometry(QtCore.QRect(110, 240, 161, 16))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.minimMaximIMLcomboBox = QtGui.QComboBox(self.vulnerability2tab)
        self.minimMaximIMLcomboBox.setGeometry(QtCore.QRect(290, 240, 241, 22))
        self.minimMaximIMLcomboBox.setObjectName(_fromUtf8("minimMaximIMLcomboBox"))
        self.line = QtGui.QFrame(self.vulnerability2tab)
        self.line.setGeometry(QtCore.QRect(110, 330, 581, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.vulnerability2tab)
        self.line_2.setGeometry(QtCore.QRect(110, 170, 571, 31))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.PredictionModel.addTab(self.vulnerability2tab, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.label_77 = QtGui.QLabel(self.tab_6)
        self.label_77.setGeometry(QtCore.QRect(230, 40, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.costTableWidget = QtGui.QTableWidget(self.tab_6)
        self.costTableWidget.setGeometry(QtCore.QRect(80, 110, 641, 401))
        self.costTableWidget.setObjectName(_fromUtf8("costTableWidget"))
        self.costTableWidget.setColumnCount(0)
        self.costTableWidget.setRowCount(0)
        self.updateCostAreaButton = QtGui.QPushButton(self.tab_6)
        self.updateCostAreaButton.setGeometry(QtCore.QRect(480, 550, 93, 28))
        self.updateCostAreaButton.setObjectName(_fromUtf8("updateCostAreaButton"))
        self.lineEdit_5 = QtGui.QLineEdit(self.tab_6)
        self.lineEdit_5.setGeometry(QtCore.QRect(490, 610, 211, 22))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.label_39 = QtGui.QLabel(self.tab_6)
        self.label_39.setGeometry(QtCore.QRect(332, 610, 121, 20))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.PredictionModel.addTab(self.tab_6, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_19 = QtGui.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(360, 80, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(140, 110, 51, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.IdDamageComboBox_2 = QtGui.QComboBox(self.tab_2)
        self.IdDamageComboBox_2.setGeometry(QtCore.QRect(190, 130, 201, 21))
        self.IdDamageComboBox_2.setObjectName(_fromUtf8("IdDamageComboBox_2"))
        self.label_21 = QtGui.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(140, 190, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(250, 190, 113, 22))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.pushButton_3 = QtGui.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 230, 93, 28))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.label_22 = QtGui.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(140, 290, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.loadHazardButton_2 = QtGui.QPushButton(self.tab_2)
        self.loadHazardButton_2.setGeometry(QtCore.QRect(260, 280, 93, 28))
        self.loadHazardButton_2.setObjectName(_fromUtf8("loadHazardButton_2"))
        self.calculateHarzadPushButton_2 = QtGui.QPushButton(self.tab_2)
        self.calculateHarzadPushButton_2.setGeometry(QtCore.QRect(270, 320, 93, 30))
        self.calculateHarzadPushButton_2.setObjectName(_fromUtf8("calculateHarzadPushButton_2"))
        self.PredictionModel.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.label_23 = QtGui.QLabel(self.tab_5)
        self.label_23.setGeometry(QtCore.QRect(120, 100, 31, 21))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.comboBox_3 = QtGui.QComboBox(self.tab_5)
        self.comboBox_3.setGeometry(QtCore.QRect(160, 100, 271, 22))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.label_24 = QtGui.QLabel(self.tab_5)
        self.label_24.setGeometry(QtCore.QRect(130, 180, 53, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.tab_5)
        self.label_25.setGeometry(QtCore.QRect(120, 270, 91, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.tab_5)
        self.label_26.setGeometry(QtCore.QRect(130, 330, 91, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.overviewHazardValuelineEdit = QtGui.QLineEdit(self.tab_5)
        self.overviewHazardValuelineEdit.setGeometry(QtCore.QRect(230, 180, 251, 22))
        self.overviewHazardValuelineEdit.setObjectName(_fromUtf8("overviewHazardValuelineEdit"))
        self.oververviewVulnerabilitylineEdit = QtGui.QLineEdit(self.tab_5)
        self.oververviewVulnerabilitylineEdit.setGeometry(QtCore.QRect(230, 270, 251, 22))
        self.oververviewVulnerabilitylineEdit.setObjectName(_fromUtf8("oververviewVulnerabilitylineEdit"))
        self.loverviewDamage = QtGui.QLineEdit(self.tab_5)
        self.loverviewDamage.setGeometry(QtCore.QRect(230, 330, 251, 22))
        self.loverviewDamage.setObjectName(_fromUtf8("loverviewDamage"))
        self.PredictionModel.addTab(self.tab_5, _fromUtf8(""))
        self.tabinter = QtGui.QWidget()
        self.tabinter.setObjectName(_fromUtf8("tabinter"))
        self.label_3 = QtGui.QLabel(self.tabinter)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 53, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tabinter)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tabinter)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 53, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.comboBoxFromLayer = QtGui.QComboBox(self.tabinter)
        self.comboBoxFromLayer.setGeometry(QtCore.QRect(90, 70, 161, 22))
        self.comboBoxFromLayer.setObjectName(_fromUtf8("comboBoxFromLayer"))
        self.comboBoxFromElement = QtGui.QComboBox(self.tabinter)
        self.comboBoxFromElement.setGeometry(QtCore.QRect(90, 100, 161, 22))
        self.comboBoxFromElement.setObjectName(_fromUtf8("comboBoxFromElement"))
        self.label_6 = QtGui.QLabel(self.tabinter)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 53, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.comboBoxToLayer = QtGui.QComboBox(self.tabinter)
        self.comboBoxToLayer.setGeometry(QtCore.QRect(90, 150, 161, 22))
        self.comboBoxToLayer.setObjectName(_fromUtf8("comboBoxToLayer"))
        self.label_10 = QtGui.QLabel(self.tabinter)
        self.label_10.setGeometry(QtCore.QRect(10, 220, 71, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tabinter)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 210, 161, 22))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.pushButton_Interdependencies = QtGui.QPushButton(self.tabinter)
        self.pushButton_Interdependencies.setGeometry(QtCore.QRect(50, 280, 211, 81))
        self.pushButton_Interdependencies.setObjectName(_fromUtf8("pushButton_Interdependencies"))
        self.PredictionModel.addTab(self.tabinter, _fromUtf8(""))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 1)
        SeismicRisk_dockwidget_base.setWidget(self.dockWidgetContents)

        self.retranslateUi(SeismicRisk_dockwidget_base)
        self.PredictionModel.setCurrentIndex(5)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SeismicRisk_dockwidget_base)

    def retranslateUi(self, SeismicRisk_dockwidget_base):
        SeismicRisk_dockwidget_base.setWindowTitle(_translate("SeismicRisk_dockwidget_base", "Seismic Risk Calculator", None))
        self.PredictionModel.setAccessibleName(_translate("SeismicRisk_dockwidget_base", "Vulnerability valiues", None))
        self.label_28.setText(_translate("SeismicRisk_dockwidget_base", "Name of layer:", None))
        self.label_2.setText(_translate("SeismicRisk_dockwidget_base", "Type of layer:", None))
        self.pushLayerButton.setText(_translate("SeismicRisk_dockwidget_base", "Add ", None))
        self.eraseLayerButton.setText(_translate("SeismicRisk_dockwidget_base", "Erase ", None))
        self.updateLayerButton.setText(_translate("SeismicRisk_dockwidget_base", "Update", None))
        self.alignLayerspushButton.setText(_translate("SeismicRisk_dockwidget_base", "Align Layers", None))
        self.PredictionModel.setTabText(self.PredictionModel.indexOf(self.tab_3), _translate("SeismicRisk_dockwidget_base", "Layers", None))
        self.label_11.setText(_translate("SeismicRisk_dockwidget_base", "Id:", None))
        self.label_16.setText(_translate("SeismicRisk_dockwidget_base", "Hazard", None))
        self.label_29.setText(_translate("SeismicRisk_dockwidget_base", "             HM: details", None))
        self.label_30.setText(_translate("SeismicRisk_dockwidget_base", "Values:", None))
        self.saveHazardModelButton.setText(_translate("SeismicRisk_dockwidget_base", "Save", None))
        self.label_13.setText(_translate("SeismicRisk_dockwidget_base", "Hazard Value:", None))
        self.label_32.setText(_translate("SeismicRisk_dockwidget_base", "R", None))
        self.label_33.setText(_translate("SeismicRisk_dockwidget_base", "S", None))
        self.saveHazardParametersPushButton.setText(_translate("SeismicRisk_dockwidget_base", "Save", None))
        self.label_12.setText(_translate("SeismicRisk_dockwidget_base", "Hazard Model", None))
        self.loadHazardButton.setText(_translate("SeismicRisk_dockwidget_base", "Load", None))
        self.calculateHarzadPushButton.setText(_translate("SeismicRisk_dockwidget_base", "Calculate", None))
        self.label_35.setText(_translate("SeismicRisk_dockwidget_base", "Hazard  Objects", None))
        self.label_34.setText(_translate("SeismicRisk_dockwidget_base", "Epicenter", None))
        self.LoadEpicenterpushButton.setText(_translate("SeismicRisk_dockwidget_base", "Load Epicenter", None))
        self.label_31.setText(_translate("SeismicRisk_dockwidget_base", "M", None))
        self.PredictionModel.setTabText(self.PredictionModel.indexOf(self.tab), _translate("SeismicRisk_dockwidget_base", "Hazard", None))
        self.resilienceButton.setText(_translate("SeismicRisk_dockwidget_base", " Calculate Methodology", None))
        self.label_9.setText(_translate("SeismicRisk_dockwidget_base", "Id", None))
        self.deleteButton.setText(_translate("SeismicRisk_dockwidget_base", "Delete", None))
        self.readButton.setText(_translate("SeismicRisk_dockwidget_base", "Read", None))
        self.pushButton.setText(_translate("SeismicRisk_dockwidget_base", "Add", None))
        self.updateValutazione.setText(_translate("SeismicRisk_dockwidget_base", "Update Evaluation", None))
        self.label_7.setText(_translate("SeismicRisk_dockwidget_base", "Methodology Results", None))
        self.label_8.setText(_translate("SeismicRisk_dockwidget_base", "Methodology Parameters", None))
        self.label.setText(_translate("SeismicRisk_dockwidget_base", "Layer name:", None))
        self.label_17.setText(_translate("SeismicRisk_dockwidget_base", "Prediction Model", None))
        self.PredictionModel.setTabText(self.PredictionModel.indexOf(self.tab_4), _translate("SeismicRisk_dockwidget_base", "Prediction Model.", None))
        self.label_69.setText(_translate("SeismicRisk_dockwidget_base", "Description", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), _translate("SeismicRisk_dockwidget_base", "Information", None))
        item = self.tableWidget_5.verticalHeaderItem(0)
        item.setText(_translate("SeismicRisk_dockwidget_base", "1", None))
        item = self.tableWidget_5.verticalHeaderItem(1)
        item.setText(_translate("SeismicRisk_dockwidget_base", "2", None))
        item = self.tableWidget_5.verticalHeaderItem(2)
        item.setText(_translate("SeismicRisk_dockwidget_base", "3", None))
        item = self.tableWidget_5.verticalHeaderItem(3)
        item.setText(_translate("SeismicRisk_dockwidget_base", "4", None))
        item = self.tableWidget_5.verticalHeaderItem(4)
        item.setText(_translate("SeismicRisk_dockwidget_base", "5", None))
        item = self.tableWidget_5.verticalHeaderItem(5)
        item.setText(_translate("SeismicRisk_dockwidget_base", "6", None))
        item = self.tableWidget_5.verticalHeaderItem(6)
        item.setText(_translate("SeismicRisk_dockwidget_base", "7", None))
        item = self.tableWidget_5.verticalHeaderItem(7)
        item.setText(_translate("SeismicRisk_dockwidget_base", "8", None))
        item = self.tableWidget_5.verticalHeaderItem(8)
        item.setText(_translate("SeismicRisk_dockwidget_base", "9", None))
        item = self.tableWidget_5.verticalHeaderItem(9)
        item.setText(_translate("SeismicRisk_dockwidget_base", "10", None))
        item = self.tableWidget_5.verticalHeaderItem(10)
        item.setText(_translate("SeismicRisk_dockwidget_base", "11", None))
        item = self.tableWidget_5.verticalHeaderItem(11)
        item.setText(_translate("SeismicRisk_dockwidget_base", "12", None))
        item = self.tableWidget_5.verticalHeaderItem(12)
        item.setText(_translate("SeismicRisk_dockwidget_base", "13", None))
        item = self.tableWidget_5.verticalHeaderItem(13)
        item.setText(_translate("SeismicRisk_dockwidget_base", "14", None))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("SeismicRisk_dockwidget_base", "Parameter", None))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("SeismicRisk_dockwidget_base", "Type", None))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("SeismicRisk_dockwidget_base", "pk", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_14), _translate("SeismicRisk_dockwidget_base", "Vulnerability parameters", None))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("SeismicRisk_dockwidget_base", "1", None))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(_translate("SeismicRisk_dockwidget_base", "2", None))
        item = self.tableWidget_4.verticalHeaderItem(2)
        item.setText(_translate("SeismicRisk_dockwidget_base", "3", None))
        item = self.tableWidget_4.verticalHeaderItem(3)
        item.setText(_translate("SeismicRisk_dockwidget_base", "4", None))
        item = self.tableWidget_4.verticalHeaderItem(4)
        item.setText(_translate("SeismicRisk_dockwidget_base", "5", None))
        item = self.tableWidget_4.verticalHeaderItem(5)
        item.setText(_translate("SeismicRisk_dockwidget_base", "6", None))
        item = self.tableWidget_4.verticalHeaderItem(6)
        item.setText(_translate("SeismicRisk_dockwidget_base", "7", None))
        item = self.tableWidget_4.verticalHeaderItem(7)
        item.setText(_translate("SeismicRisk_dockwidget_base", "8", None))
        item = self.tableWidget_4.verticalHeaderItem(8)
        item.setText(_translate("SeismicRisk_dockwidget_base", "9", None))
        item = self.tableWidget_4.verticalHeaderItem(9)
        item.setText(_translate("SeismicRisk_dockwidget_base", "10", None))
        item = self.tableWidget_4.verticalHeaderItem(10)
        item.setText(_translate("SeismicRisk_dockwidget_base", "11", None))
        item = self.tableWidget_4.verticalHeaderItem(11)
        item.setText(_translate("SeismicRisk_dockwidget_base", "12", None))
        item = self.tableWidget_4.verticalHeaderItem(12)
        item.setText(_translate("SeismicRisk_dockwidget_base", "13", None))
        item = self.tableWidget_4.verticalHeaderItem(13)
        item.setText(_translate("SeismicRisk_dockwidget_base", "14", None))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("SeismicRisk_dockwidget_base", "Parameter", None))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("SeismicRisk_dockwidget_base", "z", None))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("SeismicRisk_dockwidget_base", "w", None))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("SeismicRisk_dockwidget_base", "f", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_15), _translate("SeismicRisk_dockwidget_base", "Fragility indicators", None))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("SeismicRisk_dockwidget_base", "1", None))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("SeismicRisk_dockwidget_base", "2", None))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("SeismicRisk_dockwidget_base", "3", None))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("SeismicRisk_dockwidget_base", "4", None))
        item = self.tableWidget_3.verticalHeaderItem(4)
        item.setText(_translate("SeismicRisk_dockwidget_base", "5", None))
        item = self.tableWidget_3.verticalHeaderItem(5)
        item.setText(_translate("SeismicRisk_dockwidget_base", "6", None))
        item = self.tableWidget_3.verticalHeaderItem(6)
        item.setText(_translate("SeismicRisk_dockwidget_base", "7", None))
        item = self.tableWidget_3.verticalHeaderItem(7)
        item.setText(_translate("SeismicRisk_dockwidget_base", "8", None))
        item = self.tableWidget_3.verticalHeaderItem(8)
        item.setText(_translate("SeismicRisk_dockwidget_base", "9", None))
        item = self.tableWidget_3.verticalHeaderItem(9)
        item.setText(_translate("SeismicRisk_dockwidget_base", "10", None))
        item = self.tableWidget_3.verticalHeaderItem(10)
        item.setText(_translate("SeismicRisk_dockwidget_base", "11", None))
        item = self.tableWidget_3.verticalHeaderItem(11)
        item.setText(_translate("SeismicRisk_dockwidget_base", "12", None))
        item = self.tableWidget_3.verticalHeaderItem(12)
        item.setText(_translate("SeismicRisk_dockwidget_base", "13", None))
        item = self.tableWidget_3.verticalHeaderItem(13)
        item.setText(_translate("SeismicRisk_dockwidget_base", "14", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("SeismicRisk_dockwidget_base", "Parameter", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("SeismicRisk_dockwidget_base", "w", None))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("SeismicRisk_dockwidget_base", "n", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_16), _translate("SeismicRisk_dockwidget_base", "Protection indicators", None))
        self.PredictionModel.setTabText(self.PredictionModel.indexOf(self.vulnerabilitydetailsttab), _translate("SeismicRisk_dockwidget_base", "Vulnerability values", None))
        self.label_14.setText(_translate("SeismicRisk_dockwidget_base", "Id", None))
        self.label_15.setText(_translate("SeismicRisk_dockwidget_base", "Type of buildings:", None))
        self.label_18.setText(_translate("SeismicRisk_dockwidget_base", "Vulnerability curves", None))
        self.label_27.setText(_translate("SeismicRisk_dockwidget_base", "Curve", None))
        self.label_36.setText(_translate("SeismicRisk_dockwidget_base", "Generate map for intensity:", None))
        self.label_37.setText(_translate("SeismicRisk_dockwidget_base", "Level of damage", None))
        self.generateMapByCurveButton.setText(_translate("SeismicRisk_dockwidget_base", "Generate map", None))
        self.assignFragilityPushButton.setText(_translate("SeismicRisk_dockwidget_base", "Assign Fragility", None))
        self.addFragilityCurveButton.setText(_translate("SeismicRisk_dockwidget_base", "Add Fragility Curve", None))
        self.deleteFragilityCurvesButton.setText(_translate("SeismicRisk_dockwidget_base", "Delete Fragility Curves", None))
        self.showAssignedFragilitiesButton.setText(_translate("SeismicRisk_dockwidget_base", "Show assigned fragilities", None))
        self.label_38.setText(_translate("SeismicRisk_dockwidget_base", "Minimum maximum pga", None))
        self.PredictionModel.setTabText(self.PredictionModel.indexOf(self.vulnerability2tab), _translate("SeismicRisk_dockwidget_base", "Vulnerabiility curves", None))
        self.label_77.setText(_translate("SeismicRisk_dockwidget_base", "Losses estimation", None))
        self.updateCostAreaButton.setText(_translate("SeismicRisk_dockwidget_base", "Set cost/area", None))
        self.label_39.setText(_translate("SeismicRisk_dockwidget_base", "Total cost (Euro)", None))
        self.PredictionModel.setTabText(self.PredictionModel.indexOf(self.tab_6), _translate("SeismicRisk_dockwidget_base", "Losses", None))
        self.label_19.setText(_translate("SeismicRisk_dockwidget_base", "Damage", None))
        self.label_20.setText(_translate("SeismicRisk_dockwidget_base", "Id:", None))
        self.label_21.setText(_translate("SeismicRisk_dockwidget_base", "Damage value", None))
        self.pushButton_3.setText(_translate("SeismicRisk_dockwidget_base", "Save", None))
        self.label_22.setText(_translate("SeismicRisk_dockwidget_base", "Damage Model", None))
        self.loadHazardButton_2.setText(_translate("SeismicRisk_dockwidget_base", "Load", None))
        self.calculateHarzadPushButton_2.setText(_translate("SeismicRisk_dockwidget_base", "Calculate", None))
        self.PredictionModel.setTabText(self.PredictionModel.indexOf(self.tab_2), _translate("SeismicRisk_dockwidget_base", "Damage", None))
        self.label_23.setText(_translate("SeismicRisk_dockwidget_base", "Id", None))
        self.label_24.setText(_translate("SeismicRisk_dockwidget_base", "Hazard", None))
        self.label_25.setText(_translate("SeismicRisk_dockwidget_base", "Vulnerability", None))
        self.label_26.setText(_translate("SeismicRisk_dockwidget_base", "Damage", None))
        self.PredictionModel.setTabText(self.PredictionModel.indexOf(self.tab_5), _translate("SeismicRisk_dockwidget_base", "Overview", None))
        self.label_3.setText(_translate("SeismicRisk_dockwidget_base", "From:", None))
        self.label_4.setText(_translate("SeismicRisk_dockwidget_base", "Interdependency calculator", None))
        self.label_5.setText(_translate("SeismicRisk_dockwidget_base", "Element:", None))
        self.label_6.setText(_translate("SeismicRisk_dockwidget_base", "To:", None))
        self.label_10.setText(_translate("SeismicRisk_dockwidget_base", "Layer name", None))
        self.pushButton_Interdependencies.setText(_translate("SeismicRisk_dockwidget_base", "Calculate interdependency", None))
        self.PredictionModel.setTabText(self.PredictionModel.indexOf(self.tabinter), _translate("SeismicRisk_dockwidget_base", "Interdependecy", None))

import resources_rc
