# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Export_AutoFields.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ExportAutoFieldsDialog(object):
    def setupUi(self, ExportAutoFieldsDialog):
        ExportAutoFieldsDialog.setObjectName(_fromUtf8("ExportAutoFieldsDialog"))
        ExportAutoFieldsDialog.resize(425, 504)
        self.verticalLayout = QtGui.QVBoxLayout(ExportAutoFieldsDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(ExportAutoFieldsDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.tblAutoFields = QtGui.QTableWidget(ExportAutoFieldsDialog)
        self.tblAutoFields.setLineWidth(1)
        self.tblAutoFields.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblAutoFields.setAlternatingRowColors(True)
        self.tblAutoFields.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblAutoFields.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tblAutoFields.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.tblAutoFields.setShowGrid(True)
        self.tblAutoFields.setGridStyle(QtCore.Qt.SolidLine)
        self.tblAutoFields.setObjectName(_fromUtf8("tblAutoFields"))
        self.tblAutoFields.setColumnCount(4)
        self.tblAutoFields.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tblAutoFields.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tblAutoFields.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tblAutoFields.setItem(3, 3, item)
        self.tblAutoFields.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tblAutoFields)
        self.chkRemoveExportedAutoFields = QtGui.QCheckBox(ExportAutoFieldsDialog)
        self.chkRemoveExportedAutoFields.setObjectName(_fromUtf8("chkRemoveExportedAutoFields"))
        self.verticalLayout.addWidget(self.chkRemoveExportedAutoFields)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(ExportAutoFieldsDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.txtExportFile = QtGui.QLineEdit(ExportAutoFieldsDialog)
        self.txtExportFile.setReadOnly(True)
        self.txtExportFile.setObjectName(_fromUtf8("txtExportFile"))
        self.horizontalLayout.addWidget(self.txtExportFile)
        self.btnOpenFileDialog = QtGui.QPushButton(ExportAutoFieldsDialog)
        self.btnOpenFileDialog.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btnOpenFileDialog.setObjectName(_fromUtf8("btnOpenFileDialog"))
        self.horizontalLayout.addWidget(self.btnOpenFileDialog)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtGui.QDialogButtonBox(ExportAutoFieldsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ExportAutoFieldsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ExportAutoFieldsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ExportAutoFieldsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ExportAutoFieldsDialog)

    def retranslateUi(self, ExportAutoFieldsDialog):
        ExportAutoFieldsDialog.setWindowTitle(_translate("ExportAutoFieldsDialog", "Export AutoFields", None))
        self.label.setText(_translate("ExportAutoFieldsDialog", "Select the AutoFields you would like to export to a JSON file:", None))
        item = self.tblAutoFields.horizontalHeaderItem(0)
        item.setText(_translate("ExportAutoFieldsDialog", "Layer", None))
        item = self.tblAutoFields.horizontalHeaderItem(1)
        item.setText(_translate("ExportAutoFieldsDialog", "Field", None))
        item = self.tblAutoFields.horizontalHeaderItem(2)
        item.setText(_translate("ExportAutoFieldsDialog", "Value/Expression", None))
        item = self.tblAutoFields.horizontalHeaderItem(3)
        item.setText(_translate("ExportAutoFieldsDialog", "Status", None))
        __sortingEnabled = self.tblAutoFields.isSortingEnabled()
        self.tblAutoFields.setSortingEnabled(False)
        item = self.tblAutoFields.item(0, 0)
        item.setText(_translate("ExportAutoFieldsDialog", "Layer1", None))
        item = self.tblAutoFields.item(0, 1)
        item.setText(_translate("ExportAutoFieldsDialog", "Field1", None))
        item = self.tblAutoFields.item(0, 2)
        item.setText(_translate("ExportAutoFieldsDialog", "area", None))
        item = self.tblAutoFields.item(0, 3)
        item.setText(_translate("ExportAutoFieldsDialog", "Enabled", None))
        item = self.tblAutoFields.item(1, 0)
        item.setText(_translate("ExportAutoFieldsDialog", "Layer4", None))
        item = self.tblAutoFields.item(1, 1)
        item.setText(_translate("ExportAutoFieldsDialog", "Field4", None))
        item = self.tblAutoFields.item(1, 2)
        item.setText(_translate("ExportAutoFieldsDialog", "area", None))
        item = self.tblAutoFields.item(1, 3)
        item.setText(_translate("ExportAutoFieldsDialog", "Enabled", None))
        item = self.tblAutoFields.item(2, 0)
        item.setText(_translate("ExportAutoFieldsDialog", "Layer2", None))
        item = self.tblAutoFields.item(2, 1)
        item.setText(_translate("ExportAutoFieldsDialog", "Field2", None))
        item = self.tblAutoFields.item(2, 2)
        item.setText(_translate("ExportAutoFieldsDialog", "length", None))
        item = self.tblAutoFields.item(2, 3)
        item.setText(_translate("ExportAutoFieldsDialog", "Disabled", None))
        item = self.tblAutoFields.item(3, 0)
        item.setText(_translate("ExportAutoFieldsDialog", "Layer3", None))
        item = self.tblAutoFields.item(3, 1)
        item.setText(_translate("ExportAutoFieldsDialog", "Field3", None))
        item = self.tblAutoFields.item(3, 2)
        item.setText(_translate("ExportAutoFieldsDialog", "x coordinate", None))
        item = self.tblAutoFields.item(3, 3)
        item.setText(_translate("ExportAutoFieldsDialog", "Enabled", None))
        self.tblAutoFields.setSortingEnabled(__sortingEnabled)
        self.chkRemoveExportedAutoFields.setText(_translate("ExportAutoFieldsDialog", "After exporting, remove exported AutoFields from my QGIS", None))
        self.label_2.setText(_translate("ExportAutoFieldsDialog", "Output file", None))
        self.btnOpenFileDialog.setText(_translate("ExportAutoFieldsDialog", "...", None))

