# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\AG\.qgis2\python\plugins\SeismicRisk\Ui_SeismicRisk_dock.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SeismicRiskDockWidget(object):
    def setupUi(self, SeismicRiskDockWidget):
        SeismicRiskDockWidget.setObjectName(_fromUtf8("SeismicRiskDockWidget"))
        SeismicRiskDockWidget.resize(1016, 880)
        SeismicRiskDockWidget.setMaximumSize(QtCore.QSize(524287, 524287))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 992, 830))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.PredictionModel = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.PredictionModel.setEnabled(True)
        self.PredictionModel.setGeometry(QtCore.QRect(50, 30, 781, 731))
        self.PredictionModel.setObjectName(_fromUtf8("PredictionModel"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_28 = QtGui.QLabel(self.tab_3)
        self.label_28.setGeometry(QtCore.QRect(80, 100, 111, 20))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.layersTableView = QtGui.QTableWidget(self.tab_3)
        self.layersTableView.setGeometry(QtCore.QRect(90, 310, 361, 71))
        self.layersTableView.setObjectName(_fromUtf8("layersTableView"))
        self.layersTableView.setColumnCount(0)
        self.layersTableView.setRowCount(0)
        self.pushLayerButton = QtGui.QPushButton(self.tab_3)
        self.pushLayerButton.setGeometry(QtCore.QRect(90, 390, 93, 28))
        self.pushLayerButton.setObjectName(_fromUtf8("pushLayerButton"))
        self.setNewConnectionShapefilePath = QtGui.QLineEdit(self.tab_3)
        self.setNewConnectionShapefilePath.setGeometry(QtCore.QRect(190, 100, 271, 22))
        self.setNewConnectionShapefilePath.setObjectName(_fromUtf8("setNewConnectionShapefilePath"))
        self.eraseLayerButton = QtGui.QPushButton(self.tab_3)
        self.eraseLayerButton.setGeometry(QtCore.QRect(210, 390, 93, 28))
        self.eraseLayerButton.setObjectName(_fromUtf8("eraseLayerButton"))
        self.updateLayerButton = QtGui.QPushButton(self.tab_3)
        self.updateLayerButton.setGeometry(QtCore.QRect(320, 390, 93, 28))
        self.updateLayerButton.setObjectName(_fromUtf8("updateLayerButton"))
        self.alignLayerspushButton = QtGui.QPushButton(self.tab_3)
        self.alignLayerspushButton.setGeometry(QtCore.QRect(130, 270, 131, 28))
        self.alignLayerspushButton.setObjectName(_fromUtf8("alignLayerspushButton"))
        self.setNewConnectionButton = QtGui.QPushButton(self.tab_3)
        self.setNewConnectionButton.setGeometry(QtCore.QRect(490, 100, 91, 31))
        self.setNewConnectionButton.setObjectName(_fromUtf8("setNewConnectionButton"))
        self.createNewConnectionButton = QtGui.QPushButton(self.tab_3)
        self.createNewConnectionButton.setGeometry(QtCore.QRect(230, 180, 93, 28))
        self.createNewConnectionButton.setObjectName(_fromUtf8("createNewConnectionButton"))
        self.runAllmodelsButtonsButton_7 = QtGui.QPushButton(self.tab_3)
        self.runAllmodelsButtonsButton_7.setGeometry(QtCore.QRect(340, 180, 93, 28))
        self.runAllmodelsButtonsButton_7.setObjectName(_fromUtf8("runAllmodelsButtonsButton_7"))
        self.label_49 = QtGui.QLabel(self.tab_3)
        self.label_49.setGeometry(QtCore.QRect(80, 140, 111, 20))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.setWorkingDirectorylineEdit = QtGui.QLineEdit(self.tab_3)
        self.setWorkingDirectorylineEdit.setGeometry(QtCore.QRect(190, 140, 271, 22))
        self.setWorkingDirectorylineEdit.setObjectName(_fromUtf8("setWorkingDirectorylineEdit"))
        self.setWorkingDirectorypushButton = QtGui.QPushButton(self.tab_3)
        self.setWorkingDirectorypushButton.setGeometry(QtCore.QRect(500, 140, 93, 28))
        self.setWorkingDirectorypushButton.setObjectName(_fromUtf8("setWorkingDirectorypushButton"))
        self.predictiveRadioButton = QtGui.QRadioButton(self.tab_3)
        self.predictiveRadioButton.setGeometry(QtCore.QRect(210, 220, 191, 20))
        self.predictiveRadioButton.setObjectName(_fromUtf8("predictiveRadioButton"))
        self.fragilitiesRadioButton = QtGui.QRadioButton(self.tab_3)
        self.fragilitiesRadioButton.setGeometry(QtCore.QRect(400, 220, 171, 20))
        self.fragilitiesRadioButton.setObjectName(_fromUtf8("fragilitiesRadioButton"))
        self.managerConnectionWidget = QtGui.QWidget(self.tab_3)
        self.managerConnectionWidget.setGeometry(QtCore.QRect(70, 0, 701, 80))
        self.managerConnectionWidget.setObjectName(_fromUtf8("managerConnectionWidget"))
        self.label_2 = QtGui.QLabel(self.managerConnectionWidget)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 91, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.connectionComboBox = QtGui.QComboBox(self.managerConnectionWidget)
        self.connectionComboBox.setGeometry(QtCore.QRect(140, 30, 231, 22))
        self.connectionComboBox.setObjectName(_fromUtf8("connectionComboBox"))
        self.connectButton = QtGui.QPushButton(self.managerConnectionWidget)
        self.connectButton.setGeometry(QtCore.QRect(400, 30, 75, 23))
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.disconnectButton = QtGui.QPushButton(self.managerConnectionWidget)
        self.disconnectButton.setGeometry(QtCore.QRect(490, 30, 75, 23))
        self.disconnectButton.setObjectName(_fromUtf8("disconnectButton"))
        self.backupdButton_8 = QtGui.QPushButton(self.managerConnectionWidget)
        self.backupdButton_8.setGeometry(QtCore.QRect(580, 30, 75, 31))
        self.backupdButton_8.setObjectName(_fromUtf8("backupdButton_8"))
        self.PredictionModel.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(100, 50, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.hazardModelWidget = QtGui.QWidget(self.tab)
        self.hazardModelWidget.setGeometry(QtCore.QRect(50, 510, 341, 211))
        self.hazardModelWidget.setObjectName(_fromUtf8("hazardModelWidget"))
        self.label_29 = QtGui.QLabel(self.hazardModelWidget)
        self.label_29.setGeometry(QtCore.QRect(-10, 20, 131, 61))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.hazardModelTextEdit = QtGui.QTextEdit(self.hazardModelWidget)
        self.hazardModelTextEdit.setGeometry(QtCore.QRect(120, 50, 191, 41))
        self.hazardModelTextEdit.setObjectName(_fromUtf8("hazardModelTextEdit"))
        self.label_30 = QtGui.QLabel(self.hazardModelWidget)
        self.label_30.setGeometry(QtCore.QRect(30, 100, 131, 21))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.valuesHazardModelTextEdit = QtGui.QTextEdit(self.hazardModelWidget)
        self.valuesHazardModelTextEdit.setGeometry(QtCore.QRect(120, 100, 191, 41))
        self.valuesHazardModelTextEdit.setObjectName(_fromUtf8("valuesHazardModelTextEdit"))
        self.saveHazardModelButton = QtGui.QPushButton(self.hazardModelWidget)
        self.saveHazardModelButton.setGeometry(QtCore.QRect(220, 150, 93, 28))
        self.saveHazardModelButton.setObjectName(_fromUtf8("saveHazardModelButton"))
        self.widget_Epicenter = QtGui.QWidget(self.tab)
        self.widget_Epicenter.setGeometry(QtCore.QRect(70, 90, 541, 331))
        self.widget_Epicenter.setObjectName(_fromUtf8("widget_Epicenter"))
        self.LoadEpicenterpushButton = QtGui.QPushButton(self.widget_Epicenter)
        self.LoadEpicenterpushButton.setGeometry(QtCore.QRect(150, 280, 93, 28))
        self.LoadEpicenterpushButton.setObjectName(_fromUtf8("LoadEpicenterpushButton"))
        self.epicenterLineEdit = QtGui.QLineEdit(self.widget_Epicenter)
        self.epicenterLineEdit.setGeometry(QtCore.QRect(110, 70, 261, 21))
        self.epicenterLineEdit.setObjectName(_fromUtf8("epicenterLineEdit"))
        self.label_34 = QtGui.QLabel(self.widget_Epicenter)
        self.label_34.setGeometry(QtCore.QRect(10, 70, 53, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_35 = QtGui.QLabel(self.widget_Epicenter)
        self.label_35.setGeometry(QtCore.QRect(10, 100, 91, 20))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.hazardObjectsComboBox = QtGui.QComboBox(self.widget_Epicenter)
        self.hazardObjectsComboBox.setGeometry(QtCore.QRect(110, 100, 291, 22))
        self.hazardObjectsComboBox.setObjectName(_fromUtf8("hazardObjectsComboBox"))
        self.label_12 = QtGui.QLabel(self.widget_Epicenter)
        self.label_12.setGeometry(QtCore.QRect(10, 140, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.hazardModelComboBox = QtGui.QComboBox(self.widget_Epicenter)
        self.hazardModelComboBox.setGeometry(QtCore.QRect(110, 140, 291, 22))
        self.hazardModelComboBox.setObjectName(_fromUtf8("hazardModelComboBox"))
        self.label_44 = QtGui.QLabel(self.widget_Epicenter)
        self.label_44.setGeometry(QtCore.QRect(10, 180, 101, 16))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.soilDetailsLineEdit = QtGui.QLineEdit(self.widget_Epicenter)
        self.soilDetailsLineEdit.setEnabled(False)
        self.soilDetailsLineEdit.setGeometry(QtCore.QRect(110, 180, 231, 22))
        self.soilDetailsLineEdit.setObjectName(_fromUtf8("soilDetailsLineEdit"))
        self.soilImportButton = QtGui.QPushButton(self.widget_Epicenter)
        self.soilImportButton.setGeometry(QtCore.QRect(350, 180, 61, 28))
        self.soilImportButton.setObjectName(_fromUtf8("soilImportButton"))
        self.loadHazardButton = QtGui.QPushButton(self.widget_Epicenter)
        self.loadHazardButton.setGeometry(QtCore.QRect(360, 220, 93, 28))
        self.loadHazardButton.setObjectName(_fromUtf8("loadHazardButton"))
        self.calculateHazadPushButton = QtGui.QPushButton(self.widget_Epicenter)
        self.calculateHazadPushButton.setGeometry(QtCore.QRect(320, 260, 93, 30))
        self.calculateHazadPushButton.setObjectName(_fromUtf8("calculateHazadPushButton"))
        self.MomentumLineEdit = QtGui.QLineEdit(self.widget_Epicenter)
        self.MomentumLineEdit.setGeometry(QtCore.QRect(100, 30, 161, 22))
        self.MomentumLineEdit.setObjectName(_fromUtf8("MomentumLineEdit"))
        self.label_31 = QtGui.QLabel(self.widget_Epicenter)
        self.label_31.setGeometry(QtCore.QRect(30, 30, 53, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.soilExportButton = QtGui.QPushButton(self.widget_Epicenter)
        self.soilExportButton.setGeometry(QtCore.QRect(420, 180, 93, 28))
        self.soilExportButton.setObjectName(_fromUtf8("soilExportButton"))
        self.widgetHazardValues = QtGui.QWidget(self.tab)
        self.widgetHazardValues.setGeometry(QtCore.QRect(420, 520, 301, 201))
        self.widgetHazardValues.setObjectName(_fromUtf8("widgetHazardValues"))
        self.label_13 = QtGui.QLabel(self.widgetHazardValues)
        self.label_13.setGeometry(QtCore.QRect(30, 50, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.hazardValueLineEdit = QtGui.QLineEdit(self.widgetHazardValues)
        self.hazardValueLineEdit.setGeometry(QtCore.QRect(110, 50, 161, 22))
        self.hazardValueLineEdit.setObjectName(_fromUtf8("hazardValueLineEdit"))
        self.label_32 = QtGui.QLabel(self.widgetHazardValues)
        self.label_32.setGeometry(QtCore.QRect(60, 80, 53, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.RvalueLineEdit = QtGui.QLineEdit(self.widgetHazardValues)
        self.RvalueLineEdit.setGeometry(QtCore.QRect(110, 80, 161, 22))
        self.RvalueLineEdit.setObjectName(_fromUtf8("RvalueLineEdit"))
        self.label_33 = QtGui.QLabel(self.widgetHazardValues)
        self.label_33.setGeometry(QtCore.QRect(60, 110, 53, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.SoilLineEdit = QtGui.QLineEdit(self.widgetHazardValues)
        self.SoilLineEdit.setGeometry(QtCore.QRect(110, 110, 161, 22))
        self.SoilLineEdit.setObjectName(_fromUtf8("SoilLineEdit"))
        self.saveHazardParametersPushButton = QtGui.QPushButton(self.widgetHazardValues)
        self.saveHazardParametersPushButton.setGeometry(QtCore.QRect(180, 150, 93, 28))
        self.saveHazardParametersPushButton.setObjectName(_fromUtf8("saveHazardParametersPushButton"))
        self.label_11 = QtGui.QLabel(self.widgetHazardValues)
        self.label_11.setGeometry(QtCore.QRect(50, 10, 51, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.IdHazardComboBox = QtGui.QComboBox(self.widgetHazardValues)
        self.IdHazardComboBox.setGeometry(QtCore.QRect(90, 20, 201, 21))
        self.IdHazardComboBox.setObjectName(_fromUtf8("IdHazardComboBox"))
        self.label_42 = QtGui.QLabel(self.tab)
        self.label_42.setGeometry(QtCore.QRect(130, 490, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.PredictionModel.addTab(self.tab, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.resilienceButton = QtGui.QPushButton(self.tab_4)
        self.resilienceButton.setGeometry(QtCore.QRect(100, 200, 191, 41))
        self.resilienceButton.setObjectName(_fromUtf8("resilienceButton"))
        self.label_17 = QtGui.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(60, 40, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.predictveIndicatorsLineEdit = QtGui.QLineEdit(self.tab_4)
        self.predictveIndicatorsLineEdit.setEnabled(False)
        self.predictveIndicatorsLineEdit.setGeometry(QtCore.QRect(220, 90, 271, 22))
        self.predictveIndicatorsLineEdit.setObjectName(_fromUtf8("predictveIndicatorsLineEdit"))
        self.label_41 = QtGui.QLabel(self.tab_4)
        self.label_41.setGeometry(QtCore.QRect(90, 100, 121, 16))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.fragindexportButton = QtGui.QPushButton(self.tab_4)
        self.fragindexportButton.setGeometry(QtCore.QRect(620, 90, 93, 28))
        self.fragindexportButton.setObjectName(_fromUtf8("fragindexportButton"))
        self.widgetPredictionModelResults = QtGui.QWidget(self.tab_4)
        self.widgetPredictionModelResults.setGeometry(QtCore.QRect(100, 440, 291, 161))
        self.widgetPredictionModelResults.setObjectName(_fromUtf8("widgetPredictionModelResults"))
        self.label_43 = QtGui.QLabel(self.widgetPredictionModelResults)
        self.label_43.setGeometry(QtCore.QRect(50, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.tableViewMethodology = QtGui.QTableWidget(self.widgetPredictionModelResults)
        self.tableViewMethodology.setGeometry(QtCore.QRect(10, 80, 241, 81))
        self.tableViewMethodology.setObjectName(_fromUtf8("tableViewMethodology"))
        self.tableViewMethodology.setColumnCount(0)
        self.tableViewMethodology.setRowCount(0)
        self.label_9 = QtGui.QLabel(self.widgetPredictionModelResults)
        self.label_9.setGeometry(QtCore.QRect(30, 50, 21, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.idComboBox = QtGui.QComboBox(self.widgetPredictionModelResults)
        self.idComboBox.setGeometry(QtCore.QRect(70, 50, 141, 22))
        self.idComboBox.setObjectName(_fromUtf8("idComboBox"))
        self.updateValutazione = QtGui.QPushButton(self.tab_4)
        self.updateValutazione.setGeometry(QtCore.QRect(150, 620, 121, 21))
        self.updateValutazione.setObjectName(_fromUtf8("updateValutazione"))
        self.widget_4 = QtGui.QWidget(self.tab_4)
        self.widget_4.setGeometry(QtCore.QRect(120, 270, 351, 171))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.predictionmodelparameterslabel = QtGui.QLabel(self.widget_4)
        self.predictionmodelparameterslabel.setGeometry(QtCore.QRect(30, 30, 181, 21))
        self.predictionmodelparameterslabel.setObjectName(_fromUtf8("predictionmodelparameterslabel"))
        self.tableWidgetParameters = QtGui.QTableWidget(self.widget_4)
        self.tableWidgetParameters.setGeometry(QtCore.QRect(40, 60, 231, 101))
        self.tableWidgetParameters.setObjectName(_fromUtf8("tableWidgetParameters"))
        self.tableWidgetParameters.setColumnCount(0)
        self.tableWidgetParameters.setRowCount(0)
        self.fragindimportButton = QtGui.QPushButton(self.tab_4)
        self.fragindimportButton.setGeometry(QtCore.QRect(510, 90, 93, 28))
        self.fragindimportButton.setObjectName(_fromUtf8("fragindimportButton"))
        self.label = QtGui.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(130, 140, 53, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.MPredictiveModelLineEdit = QtGui.QLineEdit(self.tab_4)
        self.MPredictiveModelLineEdit.setGeometry(QtCore.QRect(190, 140, 113, 22))
        self.MPredictiveModelLineEdit.setObjectName(_fromUtf8("MPredictiveModelLineEdit"))
        self.PredictionModel.addTab(self.tab_4, _fromUtf8(""))
        self.vulnerabilitydetailsttab = QtGui.QWidget()
        self.vulnerabilitydetailsttab.setObjectName(_fromUtf8("vulnerabilitydetailsttab"))
        self.tabWidget = QtGui.QTabWidget(self.vulnerabilitydetailsttab)
        self.tabWidget.setGeometry(QtCore.QRect(40, 20, 741, 691))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_13 = QtGui.QWidget()
        self.tab_13.setEnabled(True)
        self.tab_13.setObjectName(_fromUtf8("tab_13"))
        self.formLayout = QtGui.QFormLayout(self.tab_13)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_69 = QtGui.QLabel(self.tab_13)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_69)
        self.lineEdit_9 = QtGui.QLineEdit(self.tab_13)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_9)
        self.tabWidget.addTab(self.tab_13, _fromUtf8(""))
        self.tab_14 = QtGui.QWidget()
        self.tab_14.setObjectName(_fromUtf8("tab_14"))
        self.tableWidget_5 = QtGui.QTableWidget(self.tab_14)
        self.tableWidget_5.setGeometry(QtCore.QRect(70, 40, 491, 471))
        self.tableWidget_5.setObjectName(_fromUtf8("tableWidget_5"))
        self.tableWidget_5.setColumnCount(3)
        self.tableWidget_5.setRowCount(14)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        self.buttonBox_3 = QtGui.QDialogButtonBox(self.tab_14)
        self.buttonBox_3.setGeometry(QtCore.QRect(370, 530, 193, 28))
        self.buttonBox_3.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_3.setObjectName(_fromUtf8("buttonBox_3"))
        self.tabWidget.addTab(self.tab_14, _fromUtf8(""))
        self.tab_15 = QtGui.QWidget()
        self.tab_15.setObjectName(_fromUtf8("tab_15"))
        self.tableWidget_4 = QtGui.QTableWidget(self.tab_15)
        self.tableWidget_4.setGeometry(QtCore.QRect(90, 40, 491, 471))
        self.tableWidget_4.setObjectName(_fromUtf8("tableWidget_4"))
        self.tableWidget_4.setColumnCount(4)
        self.tableWidget_4.setRowCount(14)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        self.buttonBox_2 = QtGui.QDialogButtonBox(self.tab_15)
        self.buttonBox_2.setGeometry(QtCore.QRect(390, 530, 193, 28))
        self.buttonBox_2.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName(_fromUtf8("buttonBox_2"))
        self.tabWidget.addTab(self.tab_15, _fromUtf8(""))
        self.tab_16 = QtGui.QWidget()
        self.tab_16.setObjectName(_fromUtf8("tab_16"))
        self.tableWidget_3 = QtGui.QTableWidget(self.tab_16)
        self.tableWidget_3.setGeometry(QtCore.QRect(30, 40, 491, 471))
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(14)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.buttonBox = QtGui.QDialogButtonBox(self.tab_16)
        self.buttonBox.setGeometry(QtCore.QRect(380, 530, 193, 28))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tabWidget.addTab(self.tab_16, _fromUtf8(""))
        self.PredictionModel.addTab(self.vulnerabilitydetailsttab, _fromUtf8(""))
        self.vulnerability2tab = QtGui.QWidget()
        self.vulnerability2tab.setObjectName(_fromUtf8("vulnerability2tab"))
        self.label_18 = QtGui.QLabel(self.vulnerability2tab)
        self.label_18.setGeometry(QtCore.QRect(170, 40, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_27 = QtGui.QLabel(self.vulnerability2tab)
        self.label_27.setGeometry(QtCore.QRect(140, 100, 53, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.selectCurvescomboBox = QtGui.QComboBox(self.vulnerability2tab)
        self.selectCurvescomboBox.setGeometry(QtCore.QRect(310, 100, 241, 22))
        self.selectCurvescomboBox.setObjectName(_fromUtf8("selectCurvescomboBox"))
        self.label_36 = QtGui.QLabel(self.vulnerability2tab)
        self.label_36.setGeometry(QtCore.QRect(110, 420, 171, 20))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.vulnerability2tab)
        self.label_37.setGeometry(QtCore.QRect(120, 470, 101, 20))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.levelDamagesComboBox = QtGui.QComboBox(self.vulnerability2tab)
        self.levelDamagesComboBox.setGeometry(QtCore.QRect(230, 460, 231, 22))
        self.levelDamagesComboBox.setObjectName(_fromUtf8("levelDamagesComboBox"))
        self.generateMapByCurveButton = QtGui.QPushButton(self.vulnerability2tab)
        self.generateMapByCurveButton.setGeometry(QtCore.QRect(470, 460, 131, 28))
        self.generateMapByCurveButton.setObjectName(_fromUtf8("generateMapByCurveButton"))
        self.earthquakeIntensityVulverabilityCurvesText = QtGui.QLineEdit(self.vulnerability2tab)
        self.earthquakeIntensityVulverabilityCurvesText.setGeometry(QtCore.QRect(280, 420, 113, 22))
        self.earthquakeIntensityVulverabilityCurvesText.setObjectName(_fromUtf8("earthquakeIntensityVulverabilityCurvesText"))
        self.assignFragilityPushButton = QtGui.QPushButton(self.vulnerability2tab)
        self.assignFragilityPushButton.setGeometry(QtCore.QRect(290, 340, 131, 28))
        self.assignFragilityPushButton.setObjectName(_fromUtf8("assignFragilityPushButton"))
        self.addFragilityCurveButton = QtGui.QPushButton(self.vulnerability2tab)
        self.addFragilityCurveButton.setGeometry(QtCore.QRect(260, 210, 161, 28))
        self.addFragilityCurveButton.setObjectName(_fromUtf8("addFragilityCurveButton"))
        self.deleteFragilityCurvesButton = QtGui.QPushButton(self.vulnerability2tab)
        self.deleteFragilityCurvesButton.setGeometry(QtCore.QRect(430, 210, 161, 28))
        self.deleteFragilityCurvesButton.setObjectName(_fromUtf8("deleteFragilityCurvesButton"))
        self.showAssignedFragilitiesButton = QtGui.QPushButton(self.vulnerability2tab)
        self.showAssignedFragilitiesButton.setGeometry(QtCore.QRect(420, 340, 161, 28))
        self.showAssignedFragilitiesButton.setObjectName(_fromUtf8("showAssignedFragilitiesButton"))
        self.label_38 = QtGui.QLabel(self.vulnerability2tab)
        self.label_38.setGeometry(QtCore.QRect(140, 140, 161, 16))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.minimMaximIMLcomboBox = QtGui.QComboBox(self.vulnerability2tab)
        self.minimMaximIMLcomboBox.setGeometry(QtCore.QRect(310, 130, 241, 22))
        self.minimMaximIMLcomboBox.setObjectName(_fromUtf8("minimMaximIMLcomboBox"))
        self.line = QtGui.QFrame(self.vulnerability2tab)
        self.line.setGeometry(QtCore.QRect(110, 250, 581, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.vulnerability2tab)
        self.line_2.setGeometry(QtCore.QRect(140, 70, 571, 31))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.assignedFragilitiesLinesEdit = QtGui.QLineEdit(self.vulnerability2tab)
        self.assignedFragilitiesLinesEdit.setEnabled(False)
        self.assignedFragilitiesLinesEdit.setGeometry(QtCore.QRect(270, 280, 281, 22))
        self.assignedFragilitiesLinesEdit.setObjectName(_fromUtf8("assignedFragilitiesLinesEdit"))
        self.label_45 = QtGui.QLabel(self.vulnerability2tab)
        self.label_45.setGeometry(QtCore.QRect(140, 280, 161, 16))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.label_40 = QtGui.QLabel(self.vulnerability2tab)
        self.label_40.setGeometry(QtCore.QRect(150, 180, 121, 16))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.fragilityCurvesRouteLineEdit = QtGui.QLineEdit(self.vulnerability2tab)
        self.fragilityCurvesRouteLineEdit.setEnabled(False)
        self.fragilityCurvesRouteLineEdit.setGeometry(QtCore.QRect(260, 170, 321, 22))
        self.fragilityCurvesRouteLineEdit.setObjectName(_fromUtf8("fragilityCurvesRouteLineEdit"))
        self.line_3 = QtGui.QFrame(self.vulnerability2tab)
        self.line_3.setGeometry(QtCore.QRect(120, 380, 581, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.pushButton_4 = QtGui.QPushButton(self.vulnerability2tab)
        self.pushButton_4.setGeometry(QtCore.QRect(560, 280, 93, 28))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.checkBox = QtGui.QCheckBox(self.vulnerability2tab)
        self.checkBox.setGeometry(QtCore.QRect(420, 420, 201, 20))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.fragilityCurvesResultsWidget = QtGui.QWidget(self.vulnerability2tab)
        self.fragilityCurvesResultsWidget.setGeometry(QtCore.QRect(100, 530, 321, 171))
        self.fragilityCurvesResultsWidget.setObjectName(_fromUtf8("fragilityCurvesResultsWidget"))
        self.label_47 = QtGui.QLabel(self.fragilityCurvesResultsWidget)
        self.label_47.setGeometry(QtCore.QRect(30, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.idComboBox_2 = QtGui.QComboBox(self.fragilityCurvesResultsWidget)
        self.idComboBox_2.setGeometry(QtCore.QRect(120, 50, 141, 22))
        self.idComboBox_2.setObjectName(_fromUtf8("idComboBox_2"))
        self.tableViewMethodology_2 = QtGui.QTableWidget(self.fragilityCurvesResultsWidget)
        self.tableViewMethodology_2.setGeometry(QtCore.QRect(60, 100, 231, 31))
        self.tableViewMethodology_2.setObjectName(_fromUtf8("tableViewMethodology_2"))
        self.tableViewMethodology_2.setColumnCount(0)
        self.tableViewMethodology_2.setRowCount(0)
        self.label_14 = QtGui.QLabel(self.fragilityCurvesResultsWidget)
        self.label_14.setGeometry(QtCore.QRect(50, 70, 21, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.importExportFragCurvesWidget = QtGui.QWidget(self.vulnerability2tab)
        self.importExportFragCurvesWidget.setGeometry(QtCore.QRect(410, 540, 381, 141))
        self.importExportFragCurvesWidget.setObjectName(_fromUtf8("importExportFragCurvesWidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.importExportFragCurvesWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 30, 321, 31))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.layoutPlot = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.layoutPlot.setObjectName(_fromUtf8("layoutPlot"))
        self.importFragilitiesButton = QtGui.QPushButton(self.importExportFragCurvesWidget)
        self.importFragilitiesButton.setGeometry(QtCore.QRect(60, 90, 93, 28))
        self.importFragilitiesButton.setObjectName(_fromUtf8("importFragilitiesButton"))
        self.exportFragilitiesButton = QtGui.QPushButton(self.importExportFragCurvesWidget)
        self.exportFragilitiesButton.setGeometry(QtCore.QRect(210, 90, 93, 28))
        self.exportFragilitiesButton.setObjectName(_fromUtf8("exportFragilitiesButton"))
        self.PredictionModel.addTab(self.vulnerability2tab, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.label_77 = QtGui.QLabel(self.tab_6)
        self.label_77.setGeometry(QtCore.QRect(230, 40, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.updateCostAreaButton = QtGui.QPushButton(self.tab_6)
        self.updateCostAreaButton.setGeometry(QtCore.QRect(520, 150, 93, 28))
        self.updateCostAreaButton.setObjectName(_fromUtf8("updateCostAreaButton"))
        self.widget_3 = QtGui.QWidget(self.tab_6)
        self.widget_3.setGeometry(QtCore.QRect(30, 180, 741, 441))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.label_48 = QtGui.QLabel(self.widget_3)
        self.label_48.setGeometry(QtCore.QRect(80, 10, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.costTableWidget = QtGui.QTableWidget(self.widget_3)
        self.costTableWidget.setGeometry(QtCore.QRect(70, 40, 651, 341))
        self.costTableWidget.setObjectName(_fromUtf8("costTableWidget"))
        self.costTableWidget.setColumnCount(0)
        self.costTableWidget.setRowCount(0)
        self.label_39 = QtGui.QLabel(self.widget_3)
        self.label_39.setGeometry(QtCore.QRect(260, 400, 121, 20))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.totalLosslineEdit = QtGui.QLineEdit(self.widget_3)
        self.totalLosslineEdit.setGeometry(QtCore.QRect(380, 400, 211, 22))
        self.totalLosslineEdit.setObjectName(_fromUtf8("totalLosslineEdit"))
        self.LossesConfigurationWidget = QtGui.QWidget(self.tab_6)
        self.LossesConfigurationWidget.setGeometry(QtCore.QRect(90, 70, 731, 80))
        self.LossesConfigurationWidget.setObjectName(_fromUtf8("LossesConfigurationWidget"))
        self.lossesExportButton = QtGui.QPushButton(self.LossesConfigurationWidget)
        self.lossesExportButton.setGeometry(QtCore.QRect(580, 30, 93, 28))
        self.lossesExportButton.setObjectName(_fromUtf8("lossesExportButton"))
        self.lossesImportButton = QtGui.QPushButton(self.LossesConfigurationWidget)
        self.lossesImportButton.setGeometry(QtCore.QRect(470, 30, 93, 28))
        self.lossesImportButton.setObjectName(_fromUtf8("lossesImportButton"))
        self.CostValuespushFile = QtGui.QLineEdit(self.LossesConfigurationWidget)
        self.CostValuespushFile.setGeometry(QtCore.QRect(170, 40, 281, 22))
        self.CostValuespushFile.setReadOnly(True)
        self.CostValuespushFile.setObjectName(_fromUtf8("CostValuespushFile"))
        self.label_46 = QtGui.QLabel(self.LossesConfigurationWidget)
        self.label_46.setGeometry(QtCore.QRect(50, 40, 71, 16))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.PredictionModel.addTab(self.tab_6, _fromUtf8(""))
        self.tab_damage = QtGui.QWidget()
        self.tab_damage.setObjectName(_fromUtf8("tab_damage"))
        self.label_19 = QtGui.QLabel(self.tab_damage)
        self.label_19.setGeometry(QtCore.QRect(360, 80, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.tab_damage)
        self.label_20.setGeometry(QtCore.QRect(140, 110, 51, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.IdDamageComboBox_2 = QtGui.QComboBox(self.tab_damage)
        self.IdDamageComboBox_2.setGeometry(QtCore.QRect(190, 130, 201, 21))
        self.IdDamageComboBox_2.setObjectName(_fromUtf8("IdDamageComboBox_2"))
        self.label_21 = QtGui.QLabel(self.tab_damage)
        self.label_21.setGeometry(QtCore.QRect(140, 190, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_damage)
        self.lineEdit_3.setGeometry(QtCore.QRect(250, 190, 113, 22))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.pushButton_3 = QtGui.QPushButton(self.tab_damage)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 230, 93, 28))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.label_22 = QtGui.QLabel(self.tab_damage)
        self.label_22.setGeometry(QtCore.QRect(140, 290, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.loadHazardButton_2 = QtGui.QPushButton(self.tab_damage)
        self.loadHazardButton_2.setGeometry(QtCore.QRect(260, 280, 93, 28))
        self.loadHazardButton_2.setObjectName(_fromUtf8("loadHazardButton_2"))
        self.calculateHarzadPushButton_2 = QtGui.QPushButton(self.tab_damage)
        self.calculateHarzadPushButton_2.setGeometry(QtCore.QRect(270, 320, 93, 30))
        self.calculateHarzadPushButton_2.setObjectName(_fromUtf8("calculateHarzadPushButton_2"))
        self.PredictionModel.addTab(self.tab_damage, _fromUtf8(""))
        self.tab_overview = QtGui.QWidget()
        self.tab_overview.setObjectName(_fromUtf8("tab_overview"))
        self.label_23 = QtGui.QLabel(self.tab_overview)
        self.label_23.setGeometry(QtCore.QRect(120, 100, 31, 21))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.comboBox_3 = QtGui.QComboBox(self.tab_overview)
        self.comboBox_3.setGeometry(QtCore.QRect(160, 100, 271, 22))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.label_24 = QtGui.QLabel(self.tab_overview)
        self.label_24.setGeometry(QtCore.QRect(130, 180, 53, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.tab_overview)
        self.label_25.setGeometry(QtCore.QRect(120, 270, 91, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.tab_overview)
        self.label_26.setGeometry(QtCore.QRect(130, 330, 91, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.overviewHazardValuelineEdit = QtGui.QLineEdit(self.tab_overview)
        self.overviewHazardValuelineEdit.setGeometry(QtCore.QRect(230, 180, 251, 22))
        self.overviewHazardValuelineEdit.setObjectName(_fromUtf8("overviewHazardValuelineEdit"))
        self.oververviewVulnerabilitylineEdit = QtGui.QLineEdit(self.tab_overview)
        self.oververviewVulnerabilitylineEdit.setGeometry(QtCore.QRect(230, 270, 251, 22))
        self.oververviewVulnerabilitylineEdit.setObjectName(_fromUtf8("oververviewVulnerabilitylineEdit"))
        self.loverviewDamage = QtGui.QLineEdit(self.tab_overview)
        self.loverviewDamage.setGeometry(QtCore.QRect(230, 330, 251, 22))
        self.loverviewDamage.setObjectName(_fromUtf8("loverviewDamage"))
        self.PredictionModel.addTab(self.tab_overview, _fromUtf8(""))
        self.tabinter = QtGui.QWidget()
        self.tabinter.setEnabled(False)
        self.tabinter.setObjectName(_fromUtf8("tabinter"))
        self.label_3 = QtGui.QLabel(self.tabinter)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 53, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tabinter)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tabinter)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 53, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.comboBoxFromLayer = QtGui.QComboBox(self.tabinter)
        self.comboBoxFromLayer.setGeometry(QtCore.QRect(90, 70, 161, 22))
        self.comboBoxFromLayer.setObjectName(_fromUtf8("comboBoxFromLayer"))
        self.comboBoxFromElement = QtGui.QComboBox(self.tabinter)
        self.comboBoxFromElement.setGeometry(QtCore.QRect(90, 100, 161, 22))
        self.comboBoxFromElement.setObjectName(_fromUtf8("comboBoxFromElement"))
        self.label_6 = QtGui.QLabel(self.tabinter)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 53, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.comboBoxToLayer = QtGui.QComboBox(self.tabinter)
        self.comboBoxToLayer.setGeometry(QtCore.QRect(90, 150, 161, 22))
        self.comboBoxToLayer.setObjectName(_fromUtf8("comboBoxToLayer"))
        self.label_10 = QtGui.QLabel(self.tabinter)
        self.label_10.setGeometry(QtCore.QRect(10, 220, 71, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tabinter)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 210, 161, 22))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.pushButton_Interdependencies = QtGui.QPushButton(self.tabinter)
        self.pushButton_Interdependencies.setGeometry(QtCore.QRect(50, 280, 211, 81))
        self.pushButton_Interdependencies.setObjectName(_fromUtf8("pushButton_Interdependencies"))
        self.PredictionModel.addTab(self.tabinter, _fromUtf8(""))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        SeismicRiskDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(SeismicRiskDockWidget)
        self.PredictionModel.setCurrentIndex(4)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(SeismicRiskDockWidget)

    def retranslateUi(self, SeismicRiskDockWidget):
        SeismicRiskDockWidget.setWindowTitle(_translate("SeismicRiskDockWidget", "Seismic Risk Calculator", None))
        self.PredictionModel.setAccessibleName(_translate("SeismicRiskDockWidget", "Fragility curves", None))
        self.label_28.setText(_translate("SeismicRiskDockWidget", "New connection", None))
        self.pushLayerButton.setText(_translate("SeismicRiskDockWidget", "Add ", None))
        self.eraseLayerButton.setText(_translate("SeismicRiskDockWidget", "Erase ", None))
        self.updateLayerButton.setText(_translate("SeismicRiskDockWidget", "Update", None))
        self.alignLayerspushButton.setText(_translate("SeismicRiskDockWidget", "Align Layers", None))
        self.setNewConnectionButton.setText(_translate("SeismicRiskDockWidget", "Set", None))
        self.createNewConnectionButton.setText(_translate("SeismicRiskDockWidget", "Create", None))
        self.runAllmodelsButtonsButton_7.setText(_translate("SeismicRiskDockWidget", "Run", None))
        self.label_49.setText(_translate("SeismicRiskDockWidget", "Working directory", None))
        self.setWorkingDirectorypushButton.setText(_translate("SeismicRiskDockWidget", "Set", None))
        self.predictiveRadioButton.setText(_translate("SeismicRiskDockWidget", "Seismic Predictive Model", None))
        self.fragilitiesRadioButton.setText(_translate("SeismicRiskDockWidget", "Fragilities curves", None))
        self.label_2.setText(_translate("SeismicRiskDockWidget", "Connection List", None))
        self.connectButton.setText(_translate("SeismicRiskDockWidget", "Connect", None))
        self.disconnectButton.setText(_translate("SeismicRiskDockWidget", "Disconnect", None))
        self.backupdButton_8.setText(_translate("SeismicRiskDockWidget", "Backup", None))
        self.PredictionModel.setTabText(self.PredictionModel.indexOf(self.tab_3), _translate("SeismicRiskDockWidget", "Layers", None))
        self.label_16.setText(_translate("SeismicRiskDockWidget", "Hazard", None))
        self.label_29.setText(_translate("SeismicRiskDockWidget", "             HM: details", None))
        self.label_30.setText(_translate("SeismicRiskDockWidget", "Values:", None))
        self.saveHazardModelButton.setText(_translate("SeismicRiskDockWidget", "Save", None))
        self.LoadEpicenterpushButton.setText(_translate("SeismicRiskDockWidget", "Load Epicenter", None))
        self.label_34.setText(_translate("SeismicRiskDockWidget", "Epicenter", None))
        self.label_35.setText(_translate("SeismicRiskDockWidget", "Hazard  Objects", None))
        self.label_12.setText(_translate("SeismicRiskDockWidget", "Hazard Model", None))
        self.label_44.setText(_translate("SeismicRiskDockWidget", "Soil and Faults", None))
        self.soilImportButton.setText(_translate("SeismicRiskDockWidget", "Import", None))
        self.loadHazardButton.setText(_translate("SeismicRiskDockWidget", "Load", None))
        self.calculateHazadPushButton.setText(_translate("SeismicRiskDockWidget", "Calculate", None))
        self.label_31.setText(_translate("SeismicRiskDockWidget", "M", None))
        self.soilExportButton.setText(_translate("SeismicRiskDockWidget", "Export", None))
        self.label_13.setText(_translate("SeismicRiskDockWidget", "Hazard Value:", None))
        self.label_32.setText(_translate("SeismicRiskDockWidget", "R", None))
        self.label_33.setText(_translate("SeismicRiskDockWidget", "S", None))
        self.saveHazardParametersPushButton.setText(_translate("SeismicRiskDockWidget", "Save", None))
        self.label_11.setText(_translate("SeismicRiskDockWidget", "Id:", None))
        self.label_42.setText(_translate("SeismicRiskDockWidget", "Results", None))
        self.PredictionModel.setTabText(self.PredictionModel.indexOf(self.tab), _translate("SeismicRiskDockWidget", "Hazard", None))
        self.resilienceButton.setText(_translate("SeismicRiskDockWidget", " Calculate Methodology", None))
        self.label_17.setText(_translate("SeismicRiskDockWidget", "Prediction Model", None))
        self.label_41.setText(_translate("SeismicRiskDockWidget", "Fragilities indicators", None))
        self.fragindexportButton.setText(_translate("SeismicRiskDockWidget", "Export", None))
        self.label_43.setText(_translate("SeismicRiskDockWidget", "Results", None))
        self.label_9.setText(_translate("SeismicRiskDockWidget", "Id", None))
        self.updateValutazione.setText(_translate("SeismicRiskDockWidget", "Update Evaluation", None))
        self.predictionmodelparameterslabel.setText(_translate("SeismicRiskDockWidget", "Methodology Parameters", None))
        self.fragindimportButton.setText(_translate("SeismicRiskDockWidget", "Import", None))
        self.label.setText(_translate("SeismicRiskDockWidget", "M", None))
        self.PredictionModel.setTabText(self.PredictionModel.indexOf(self.tab_4), _translate("SeismicRiskDockWidget", "Prediction Model.", None))
        self.label_69.setText(_translate("SeismicRiskDockWidget", "Description", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), _translate("SeismicRiskDockWidget", "Information", None))
        item = self.tableWidget_5.verticalHeaderItem(0)
        item.setText(_translate("SeismicRiskDockWidget", "1", None))
        item = self.tableWidget_5.verticalHeaderItem(1)
        item.setText(_translate("SeismicRiskDockWidget", "2", None))
        item = self.tableWidget_5.verticalHeaderItem(2)
        item.setText(_translate("SeismicRiskDockWidget", "3", None))
        item = self.tableWidget_5.verticalHeaderItem(3)
        item.setText(_translate("SeismicRiskDockWidget", "4", None))
        item = self.tableWidget_5.verticalHeaderItem(4)
        item.setText(_translate("SeismicRiskDockWidget", "5", None))
        item = self.tableWidget_5.verticalHeaderItem(5)
        item.setText(_translate("SeismicRiskDockWidget", "6", None))
        item = self.tableWidget_5.verticalHeaderItem(6)
        item.setText(_translate("SeismicRiskDockWidget", "7", None))
        item = self.tableWidget_5.verticalHeaderItem(7)
        item.setText(_translate("SeismicRiskDockWidget", "8", None))
        item = self.tableWidget_5.verticalHeaderItem(8)
        item.setText(_translate("SeismicRiskDockWidget", "9", None))
        item = self.tableWidget_5.verticalHeaderItem(9)
        item.setText(_translate("SeismicRiskDockWidget", "10", None))
        item = self.tableWidget_5.verticalHeaderItem(10)
        item.setText(_translate("SeismicRiskDockWidget", "11", None))
        item = self.tableWidget_5.verticalHeaderItem(11)
        item.setText(_translate("SeismicRiskDockWidget", "12", None))
        item = self.tableWidget_5.verticalHeaderItem(12)
        item.setText(_translate("SeismicRiskDockWidget", "13", None))
        item = self.tableWidget_5.verticalHeaderItem(13)
        item.setText(_translate("SeismicRiskDockWidget", "14", None))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("SeismicRiskDockWidget", "Parameter", None))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("SeismicRiskDockWidget", "Type", None))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("SeismicRiskDockWidget", "pk", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_14), _translate("SeismicRiskDockWidget", "Vulnerability parameters", None))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("SeismicRiskDockWidget", "1", None))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(_translate("SeismicRiskDockWidget", "2", None))
        item = self.tableWidget_4.verticalHeaderItem(2)
        item.setText(_translate("SeismicRiskDockWidget", "3", None))
        item = self.tableWidget_4.verticalHeaderItem(3)
        item.setText(_translate("SeismicRiskDockWidget", "4", None))
        item = self.tableWidget_4.verticalHeaderItem(4)
        item.setText(_translate("SeismicRiskDockWidget", "5", None))
        item = self.tableWidget_4.verticalHeaderItem(5)
        item.setText(_translate("SeismicRiskDockWidget", "6", None))
        item = self.tableWidget_4.verticalHeaderItem(6)
        item.setText(_translate("SeismicRiskDockWidget", "7", None))
        item = self.tableWidget_4.verticalHeaderItem(7)
        item.setText(_translate("SeismicRiskDockWidget", "8", None))
        item = self.tableWidget_4.verticalHeaderItem(8)
        item.setText(_translate("SeismicRiskDockWidget", "9", None))
        item = self.tableWidget_4.verticalHeaderItem(9)
        item.setText(_translate("SeismicRiskDockWidget", "10", None))
        item = self.tableWidget_4.verticalHeaderItem(10)
        item.setText(_translate("SeismicRiskDockWidget", "11", None))
        item = self.tableWidget_4.verticalHeaderItem(11)
        item.setText(_translate("SeismicRiskDockWidget", "12", None))
        item = self.tableWidget_4.verticalHeaderItem(12)
        item.setText(_translate("SeismicRiskDockWidget", "13", None))
        item = self.tableWidget_4.verticalHeaderItem(13)
        item.setText(_translate("SeismicRiskDockWidget", "14", None))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("SeismicRiskDockWidget", "Parameter", None))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("SeismicRiskDockWidget", "z", None))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("SeismicRiskDockWidget", "w", None))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("SeismicRiskDockWidget", "f", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_15), _translate("SeismicRiskDockWidget", "Fragility indicators", None))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("SeismicRiskDockWidget", "1", None))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("SeismicRiskDockWidget", "2", None))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("SeismicRiskDockWidget", "3", None))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("SeismicRiskDockWidget", "4", None))
        item = self.tableWidget_3.verticalHeaderItem(4)
        item.setText(_translate("SeismicRiskDockWidget", "5", None))
        item = self.tableWidget_3.verticalHeaderItem(5)
        item.setText(_translate("SeismicRiskDockWidget", "6", None))
        item = self.tableWidget_3.verticalHeaderItem(6)
        item.setText(_translate("SeismicRiskDockWidget", "7", None))
        item = self.tableWidget_3.verticalHeaderItem(7)
        item.setText(_translate("SeismicRiskDockWidget", "8", None))
        item = self.tableWidget_3.verticalHeaderItem(8)
        item.setText(_translate("SeismicRiskDockWidget", "9", None))
        item = self.tableWidget_3.verticalHeaderItem(9)
        item.setText(_translate("SeismicRiskDockWidget", "10", None))
        item = self.tableWidget_3.verticalHeaderItem(10)
        item.setText(_translate("SeismicRiskDockWidget", "11", None))
        item = self.tableWidget_3.verticalHeaderItem(11)
        item.setText(_translate("SeismicRiskDockWidget", "12", None))
        item = self.tableWidget_3.verticalHeaderItem(12)
        item.setText(_translate("SeismicRiskDockWidget", "13", None))
        item = self.tableWidget_3.verticalHeaderItem(13)
        item.setText(_translate("SeismicRiskDockWidget", "14", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("SeismicRiskDockWidget", "Parameter", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("SeismicRiskDockWidget", "w", None))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("SeismicRiskDockWidget", "n", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_16), _translate("SeismicRiskDockWidget", "Protection indicators", None))
        self.PredictionModel.setTabText(self.PredictionModel.indexOf(self.vulnerabilitydetailsttab), _translate("SeismicRiskDockWidget", "Vulnerability values", None))
        self.label_18.setText(_translate("SeismicRiskDockWidget", "Fragility curves", None))
        self.label_27.setText(_translate("SeismicRiskDockWidget", "Curve", None))
        self.label_36.setText(_translate("SeismicRiskDockWidget", "Generate map for intensity:", None))
        self.label_37.setText(_translate("SeismicRiskDockWidget", "Level of damage", None))
        self.generateMapByCurveButton.setText(_translate("SeismicRiskDockWidget", "Generate map", None))
        self.assignFragilityPushButton.setWhatsThis(_translate("SeismicRiskDockWidget", "Load the data in the input comunity layer", None))
        self.assignFragilityPushButton.setText(_translate("SeismicRiskDockWidget", "Assign Fragility", None))
        self.addFragilityCurveButton.setText(_translate("SeismicRiskDockWidget", "Add Fragility Curve", None))
        self.deleteFragilityCurvesButton.setText(_translate("SeismicRiskDockWidget", "Delete Fragility Curves", None))
        self.showAssignedFragilitiesButton.setText(_translate("SeismicRiskDockWidget", "Show assigned fragilities", None))
        self.label_38.setText(_translate("SeismicRiskDockWidget", "Minimum maximum pga", None))
        self.label_45.setText(_translate("SeismicRiskDockWidget", "Assigned fragilities", None))
        self.label_40.setText(_translate("SeismicRiskDockWidget", "Fragility curves ", None))
        self.pushButton_4.setText(_translate("SeismicRiskDockWidget", "Set", None))
        self.checkBox.setText(_translate("SeismicRiskDockWidget", "Load from hazard model", None))
        self.label_47.setText(_translate("SeismicRiskDockWidget", "Results", None))
        self.label_14.setText(_translate("SeismicRiskDockWidget", "Id", None))
        self.importFragilitiesButton.setText(_translate("SeismicRiskDockWidget", "Import", None))
        self.exportFragilitiesButton.setText(_translate("SeismicRiskDockWidget", "Export", None))
        self.PredictionModel.setTabText(self.PredictionModel.indexOf(self.vulnerability2tab), _translate("SeismicRiskDockWidget", "Fragility curves", None))
        self.label_77.setText(_translate("SeismicRiskDockWidget", "Losses estimation", None))
        self.updateCostAreaButton.setText(_translate("SeismicRiskDockWidget", "Calculate", None))
        self.label_48.setText(_translate("SeismicRiskDockWidget", "Results", None))
        self.label_39.setText(_translate("SeismicRiskDockWidget", "Total cost (Euro)", None))
        self.lossesExportButton.setText(_translate("SeismicRiskDockWidget", "Export", None))
        self.lossesImportButton.setText(_translate("SeismicRiskDockWidget", "Import", None))
        self.label_46.setText(_translate("SeismicRiskDockWidget", "Cost/Area", None))
        self.PredictionModel.setTabText(self.PredictionModel.indexOf(self.tab_6), _translate("SeismicRiskDockWidget", "Losses", None))
        self.label_19.setText(_translate("SeismicRiskDockWidget", "Damage", None))
        self.label_20.setText(_translate("SeismicRiskDockWidget", "Id:", None))
        self.label_21.setText(_translate("SeismicRiskDockWidget", "Damage value", None))
        self.pushButton_3.setText(_translate("SeismicRiskDockWidget", "Save", None))
        self.label_22.setText(_translate("SeismicRiskDockWidget", "Damage Model", None))
        self.loadHazardButton_2.setText(_translate("SeismicRiskDockWidget", "Load", None))
        self.calculateHarzadPushButton_2.setText(_translate("SeismicRiskDockWidget", "Calculate", None))
        self.label_23.setText(_translate("SeismicRiskDockWidget", "Id", None))
        self.label_24.setText(_translate("SeismicRiskDockWidget", "Hazard", None))
        self.label_25.setText(_translate("SeismicRiskDockWidget", "Vulnerability", None))
        self.label_26.setText(_translate("SeismicRiskDockWidget", "Damage", None))
        self.label_3.setText(_translate("SeismicRiskDockWidget", "From:", None))
        self.label_4.setText(_translate("SeismicRiskDockWidget", "Interdependency calculator", None))
        self.label_5.setText(_translate("SeismicRiskDockWidget", "Element:", None))
        self.label_6.setText(_translate("SeismicRiskDockWidget", "To:", None))
        self.label_10.setText(_translate("SeismicRiskDockWidget", "Layer name", None))
        self.pushButton_Interdependencies.setText(_translate("SeismicRiskDockWidget", "Calculate interdependency", None))

import resources_rc
