# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\AG\.qgis2\python\plugins\SeismicRisk\UI\building.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_soil(object):
    def setupUi(self, soil):
        soil.setObjectName(_fromUtf8("soil"))
        soil.resize(713, 747)
        self.buttonBox = QtGui.QDialogButtonBox(soil)
        self.buttonBox.setGeometry(QtCore.QRect(460, 670, 193, 28))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.tableWidget = QtGui.QTableWidget(soil)
        self.tableWidget.setGeometry(QtCore.QRect(120, 340, 491, 311))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(14)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.label_7 = QtGui.QLabel(soil)
        self.label_7.setGeometry(QtCore.QRect(130, 300, 158, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(soil)
        self.label_8.setGeometry(QtCore.QRect(110, 60, 53, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.id = QtGui.QLineEdit(soil)
        self.id.setGeometry(QtCore.QRect(190, 60, 113, 22))
        self.id.setObjectName(_fromUtf8("id"))
        self.splitter_2 = QtGui.QSplitter(soil)
        self.splitter_2.setGeometry(QtCore.QRect(190, 90, 411, 168))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.name = QtGui.QLineEdit(self.splitter_2)
        self.name.setObjectName(_fromUtf8("name"))
        self.description = QtGui.QLineEdit(self.splitter_2)
        self.description.setObjectName(_fromUtf8("description"))
        self.fragility = QtGui.QComboBox(self.splitter_2)
        self.fragility.setObjectName(_fromUtf8("fragility"))
        self.fault_2 = QtGui.QRadioButton(self.splitter_2)
        self.fault_2.setObjectName(_fromUtf8("fault_2"))
        self.fault = QtGui.QRadioButton(self.splitter_2)
        self.fault.setObjectName(_fromUtf8("fault"))
        self.soil_2 = QtGui.QRadioButton(self.splitter_2)
        self.soil_2.setObjectName(_fromUtf8("soil_2"))
        self.soil_3 = QtGui.QRadioButton(self.splitter_2)
        self.soil_3.setObjectName(_fromUtf8("soil_3"))
        self.cost = QtGui.QLineEdit(self.splitter_2)
        self.cost.setObjectName(_fromUtf8("cost"))
        self.splitter = QtGui.QSplitter(soil)
        self.splitter.setGeometry(QtCore.QRect(110, 90, 63, 171))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.label = QtGui.QLabel(self.splitter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.splitter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_4 = QtGui.QLabel(self.splitter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.splitter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_3 = QtGui.QLabel(self.splitter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_6 = QtGui.QLabel(self.splitter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.buttonBox_2 = QtGui.QAction(soil)
        self.buttonBox_2.setObjectName(_fromUtf8("buttonBox_2"))

        self.retranslateUi(soil)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), self.tableWidget.show)
        QtCore.QMetaObject.connectSlotsByName(soil)

    def retranslateUi(self, soil):
        soil.setWindowTitle(_translate("soil", "Form", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("soil", "1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("soil", "2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("soil", "3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("soil", "4", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("soil", "5", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("soil", "6", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("soil", "7", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("soil", "8", None))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("soil", "9", None))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("soil", "10", None))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("soil", "11", None))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("soil", "12", None))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("soil", "13", None))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("soil", "14", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("soil", "w", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("soil", "z", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("soil", "f", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("soil", "n", None))
        self.label_7.setText(_translate("soil", "Seismic Predictive Model", None))
        self.label_8.setText(_translate("soil", "Id", None))
        self.fault_2.setText(_translate("soil", "not fault", None))
        self.fault.setText(_translate("soil", "Fault", None))
        self.soil_2.setText(_translate("soil", "no soil", None))
        self.soil_3.setText(_translate("soil", "soil", None))
        self.label.setText(_translate("soil", "Name", None))
        self.label_2.setText(_translate("soil", "Description", None))
        self.label_4.setText(_translate("soil", "Fragilities", None))
        self.label_5.setText(_translate("soil", "Fault", None))
        self.label_3.setText(_translate("soil", "Soil", None))
        self.label_6.setText(_translate("soil", "Cost", None))
        self.buttonBox_2.setText(_translate("soil", "action", None))

